#!/usr/bin/env python

import physvis


def main():
    N_x = [100, 100]
    dxs = [0.1, 0.1]
    x = physvis.space.normal(N_x, dxs)
    dt = 0.01

    system = physvis.ClassicalSystem(
        [
            physvis.ClassicalParticle(x, (1, 0), (0, 2), mass=30),
            physvis.ClassicalParticle(x, (-1, 0), (0, -2), mass=10),
        ],
        [physvis.force.gravity],
    )

    simulation = physvis.Simulation(system, dt, window_size=(1280, 1280))

    simulation.run()


if __name__ == '__main__':
    main()
