#!/usr/bin/env python

import physvis


def main(window_size=(1280, 640)):
    N_x = [100, 100]
    dxs = [0.1, 0.1]
    x = physvis.space.normal(N_x, dxs)
    dt = 0.01

    system = physvis.ClassicalSystem(
        [physvis.ClassicalParticle(x, (-5, -5), (5, 5))],
        [physvis.force.uniform_gravity],
    )

    simulation = physvis.Simulation(system, dt)

    simulation.run()


if __name__ == '__main__':
    main()
