#!/usr/bin/env python

import physvis


def main():
    N_x = [100, 100]
    dxs = [0.1, 0.1]
    x = physvis.space.normal(N_x, dxs)
    dt = 0.01

    system = physvis.ClassicalSystem(
        [
            physvis.ClassicalParticle(x, (-5, 0), (7, 7)),
            physvis.ClassicalParticle(x, (-5, 0), (0, 7)),
        ],
        [physvis.force.uniform_gravity],
    )

    simulation = physvis.Simulation(system, dt, window_size=(1080, 1080))

    simulation.run()


if __name__ == '__main__':
    main()
