#!/usr/bin/env python

import physvis


def main(window_size=(1080, 540)):
    N_x = [100, 100]
    dxs = [0.1, 0.1]
    x = physvis.space.normal(N_x, dxs)
    dt = 0.001

    particle = physvis.QuantumParticle.wavepacket(
        (10, 0),
        (0, 0),
        1.0,
        x,
    )

    V = physvis.potential.barrier(4, 0.5, 400, x) + physvis.potential.barrier(-4, 0.5, 400, x)

    quantum_system = physvis.QuantumSystem([particle], V)
    simulation = physvis.Simulation(quantum_system, dt, window_size=(1080, 520))

    simulation.run()


if __name__ == '__main__':
    main()
