#!/usr/bin/env python

import physvis


def main(window_size=(1280, 640)):
    N_x = [100, 100]
    dxs = [0.1, 0.1]
    x = physvis.space.normal(N_x, dxs)
    dt = 0.005

    particle = physvis.QuantumParticle.wavepacket(
        (20, 0),
        (-2.5, 0),
        1.0,
        x,
    )

    V = physvis.potential.barrier(0.75, 0.1, 500, x)

    quantum_system = physvis.QuantumSystem([particle], V)
    simulation = physvis.Simulation(quantum_system, dt)

    simulation.run()


if __name__ == '__main__':
    main()
